
import "rsuite/dist/rsuite.min.css";
import "../../styles/globals.css";
import { Inter } from "next/font/google";
import { CustomProvider } from "rsuite";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <head>
        <style>{inter.css}</style>
      </head>
      <body className={inter.className}>
        <Navbar/>
          <CustomProvider>{children}</CustomProvider>
      <Footer/>
      </body>
    </html>
  );
}

